weights: /data/ylf/yolo_demo/weight/yolov5x.tmp
cfg: /data/ylf/yolo_demo/models/yolov5s.yaml
data: /data/ylf/yolo_demo/data/ab.yaml
hyp: /data/ylf/yolo_demo/data/hyp.scratch.yaml
epochs: 150
batch_size: 16
img_size:
- 256
- 256
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: true
image_weights: true
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 0
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/exp45
total_batch_size: 16
